Implement sms sender to send sms to external url
sflpro/notifier pull request #170
Opened 2021-06-25 08:36 UTC by nazaretyan

2021-06-25 15:30 UTC, mkrtchyanh reviewed
God job!

2021-06-25 15:30 UTC, mkrtchyanh commented on infra/infra-integrations/infra-integrations-sms/src/main/java/com/sflpro/notifier/externalclients/sms/webhook/WebhookSimpleSmsSender.java
> +    public WebhookSimpleSmsSender(final WebhookApiRestClient apiRestClient) {
Maybe package access is better?

2021-06-28 15:16 UTC, nazaretyan commented on infra/infra-integrations/infra-integrations-sms/src/main/java/com/sflpro/notifier/externalclients/sms/webhook/WebhookSimpleSmsSender.java
> +    public WebhookSimpleSmsSender(final WebhookApiRestClient apiRestClient) {
Agree!! Will change to package access

2021-06-30 07:51 UTC, mikron requested changes

2021-06-30 07:51 UTC, mikron commented on infra/infra-integrations/infra-integrations-sms/pom.xml
> +        <dependency>
Do we need this dependency now?

2021-06-30 11:20 UTC, nazaretyan commented on infra/infra-integrations/infra-integrations-sms/pom.xml
> +        <dependency>
@mikron jan removed

2021-06-30 11:20 UTC, mikron approved these changes

2021-07-08 13:36 UTC, dnavre commented
testing travis integration

2021-07-09 10:34 UTC, merged